variables:
  EXTRA_VERSION: "-git"

# -----------------------------
# Docker build for all branches
# -----------------------------

linux64_docker:
  image: onelab/ubuntu16.04
  tags:
    - linux64
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - ctest -j 4 --output-on-failure

# ------------------------------------------
# Official Linux builds (master branch only)
# ------------------------------------------

.linux_official_petsc_complex: &ref_linux_official_petsc_complex
  only:
    - master
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGETDP_EXTRA_VERSION=$EXTRA_VERSION -DCMAKE_PREFIX_PATH=/usr/local -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc-3.7.5 -DSLEPC_DIR=/home/geuzaine/src/slepc-3.7.3 ..
    - make package -j 2
    - /usr/local/bin/ctest -D Experimental -j 2 --output-on-failure
    - PKG=`ls getdp-*.tar*`; scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/beta/${PKG/\.tar\.gz/c\.tgz}

.linux_official_petsc_real: &ref_linux_official_petsc_real
  only:
    - master
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGETDP_EXTRA_VERSION=$EXTRA_VERSION -DCMAKE_PREFIX_PATH=/usr/local -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=real_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc-3.7.5 -DSLEPC_DIR=/home/geuzaine/src/slepc-3.7.3 ..
    - make package -j 2
    - /usr/local/bin/ctest -D Experimental -j 2 --output-on-failure
    - PKG=`ls getdp-*.tar*`; scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/beta/${PKG/\.tar\.gz/r\.tgz}

.linux_official_petsc_real_mh: &ref_linux_official_petsc_real_mh
  only:
    - master
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGETDP_EXTRA_VERSION=$EXTRA_VERSION -DCMAKE_PREFIX_PATH=/usr/local -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=real_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc-3.7.5 -DSLEPC_DIR=/home/geuzaine/src/slepc-3.7.3 -DENABLE_MULTIHARMONIC=1 ..
    - make package -j 2
    - /usr/local/bin/ctest -D Experimental -j 2 --output-on-failure
    - PKG=`ls getdp-*.tar*`; scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/beta/${PKG/\.tar\.gz/r-MH\.tgz}

linux64_official_petsc_complex:
  <<: *ref_linux_official_petsc_complex
  tags:
    - linux64
    - official

linux64_official_petsc_real:
  <<: *ref_linux_official_petsc_real
  tags:
    - linux64
    - official

linux64_official_petsc_real_mh:
  <<: *ref_linux_official_petsc_real_mh
  tags:
    - linux64
    - official

.linux32_official_petsc_complex:
  <<: *ref_linux_official_petsc_complex
  tags:
    - linux32
    - official

.linux32_official_petsc_real:
  <<: *ref_linux_official_petsc_real
  tags:
    - linux32
    - official

.linux32_official_petsc_real_mh:
  <<: *ref_linux_official_petsc_real_mh
  tags:
    - linux32
    - official

# --------------------------------------------
# Official Windows builds (master branch only)
# --------------------------------------------

.windows_official_petsc_complex: &ref_windows_official_petsc_complex
  only:
    - master
  script:
    - md build
    - cd build
    - bash -c "/usr/bin/cmake -DGETDP_EXTRA_VERSION=$EXTRA_VERSION -DCMAKE_PREFIX_PATH='/usr/local;/usr/mingw32/sys-root/mingw' -DCMAKE_C_COMPILER=/usr/bin/mingw32-gcc.exe -DCMAKE_CXX_COMPILER=/usr/bin/mingw32-g++.exe -DCMAKE_Fortran_COMPILER=/usr/bin/mingw32-gfortran.exe -DCMAKE_RC_COMPILER=/usr/bin/mingw32-windres.exe -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc-3.7.5 -DSLEPC_DIR=/home/geuzaine/src/slepc-3.7.3 .."
    - bash -c "/usr/bin/make package -j 2"
    - bash -c "/usr/bin/ctest -D Experimental -j 2 --output-on-failure"
    - bash -c "PKG=`ls getdp-*.zip`; /usr/bin/scp -o StrictHostKeyChecking=no -i /home/geuzaine/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/beta/${PKG/\.zip/c\.zip}"

.windows_official_petsc_real: &ref_windows_official_petsc_real
  only:
    - master
  script:
    - md build
    - cd build
    - bash -c "/usr/bin/cmake -DGETDP_EXTRA_VERSION=$EXTRA_VERSION -DCMAKE_PREFIX_PATH='/usr/local;/usr/mingw32/sys-root/mingw' -DCMAKE_C_COMPILER=/usr/bin/mingw32-gcc.exe -DCMAKE_CXX_COMPILER=/usr/bin/mingw32-g++.exe -DCMAKE_Fortran_COMPILER=/usr/bin/mingw32-gfortran.exe -DCMAKE_RC_COMPILER=/usr/bin/mingw32-windres.exe -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=real_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc-3.7.5 -DSLEPC_DIR=/home/geuzaine/src/slepc-3.7.3 .."
    - bash -c "/usr/bin/make package -j 2"
    - bash -c "/usr/bin/ctest -D Experimental -j 2 --output-on-failure"
    - bash -c "PKG=`ls getdp-*.zip`; /usr/bin/scp -o StrictHostKeyChecking=no -i /home/geuzaine/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/beta/${PKG/\.zip/r\.zip}"

.windows_official_petsc_real_mh: &ref_windows_official_petsc_real_mh
  only:
    - master
  script:
    - md build
    - cd build
    - bash -c "/usr/bin/cmake -DGETDP_EXTRA_VERSION=$EXTRA_VERSION -DCMAKE_PREFIX_PATH='/usr/local;/usr/mingw32/sys-root/mingw' -DCMAKE_C_COMPILER=/usr/bin/mingw32-gcc.exe -DCMAKE_CXX_COMPILER=/usr/bin/mingw32-g++.exe -DCMAKE_Fortran_COMPILER=/usr/bin/mingw32-gfortran.exe -DCMAKE_RC_COMPILER=/usr/bin/mingw32-windres.exe -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=real_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc-3.7.5 -DSLEPC_DIR=/home/geuzaine/src/slepc-3.7.3 -DENABLE_MULTIHARMONIC=1 .."
    - bash -c "/usr/bin/make package -j 2"
    - bash -c "/usr/bin/ctest -D Experimental -j 2 --output-on-failure"
    - bash -c "PKG=`ls getdp-*.zip`; /usr/bin/scp -o StrictHostKeyChecking=no -i /home/geuzaine/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/beta/${PKG/\.zip/r-MH\.zip}"

windows64_official_petsc_complex:
  <<: *ref_windows_official_petsc_complex
  tags:
    - windows64
    - official

windows64_official_petsc_real:
  <<: *ref_windows_official_petsc_real
  tags:
    - windows64
    - official

windows64_official_petsc_real_mh:
  <<: *ref_windows_official_petsc_real_mh
  tags:
    - windows64
    - official

windows32_official_petsc_complex:
  <<: *ref_windows_official_petsc_complex
  tags:
    - windows32
    - official

windows32_official_petsc_real:
  <<: *ref_windows_official_petsc_real
  tags:
    - windows32
    - official

windows32_official_petsc_real_mh:
  <<: *ref_windows_official_petsc_real_mh
  tags:
    - windows32
    - official
