linux64_gcc:
  image: onelab/ubuntu16.04
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - ctest -j 4 --output-on-failure

windows64_msvc:
  tags:
    - windows
  script:
    - md build
    - cd build
    - cmake -DENABLE_FORTRAN=0 ..
    - msbuild package.vcxproj
