# GetDP - Copyright (C) 1997-2019 P. Dular and C. Geuzaine, University of Liege
#
# See the LICENSE.txt file for license information. Please report all
# issues on https://gitlab.onelab.info/getdp/getdp/issues.

variables:
  EXTRA_OPTION: ""

# ---------------------------------------------
# Continuous integation builds for all branches
# ---------------------------------------------

linux64_ci:
  image: onelab/ubuntu18.04
  script:
    - mkdir build
    - cd build
    - cmake ${EXTRA_OPTION} ..
    - make -j 8
    - ctest -j 8 --output-on-failure
  tags:
    - linux64
    - docker
  except:
    - tags

windows64_ci:
  script:
    - md build
    - cd build
    - bash -c "/usr/bin/cmake -DCMAKE_PREFIX_PATH='/usr/local;/usr/x86_64-w64-mingw32/sys-root/mingw' -DCMAKE_C_COMPILER=/usr/bin/x86_64-w64-mingw32-gcc.exe -DCMAKE_CXX_COMPILER=/usr/bin/x86_64-w64-mingw32-g++.exe -DCMAKE_Fortran_COMPILER=/usr/bin/x86_64-w64-mingw32-gfortran.exe -DCMAKE_RC_COMPILER=/usr/bin/x86_64-w64-mingw32-windres.exe -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/home/Administrateur/petsc -DSLEPC_DIR=/home/Administrateur/slepc ${EXTRA_OPTION} .."
    - bash -c "/usr/bin/make -j 8"
    - bash -c "/usr/bin/ctest -j 8 --output-on-failure"
  tags:
    - windows64
    - shared
  except:
    - tags

linux64_beta_petsc_complex:
  image: onelab/debian.wheezy.64bit
  script:
    - echo "$SSH_TOKEN" > ~/.ssh/id_rsa
    - echo "Host *" > ~/.ssh/config
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
    - chmod 700 ~/.ssh/id_rsa ~/.ssh/config
    - mkdir build
    - cd build
    - cmake -DGETDP_EXTRA_BUILD_NAME=-PetscComplex -DGETDP_HOST=getdp.info -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/petsc-3.10.2 -DSLEPC_DIR=/slepc-3.10.1 -DBLAS_LAPACK_LIBRARIES='/usr/local/lib/libopenblas.a;/usr/local/lib64/libgfortran.a;/usr/local/lib64/libquadmath.a;-lpthread;-static-libstdc++' ${EXTRA_OPTION} ..
    - make package -j 8
    - PKG=`ls getdp-*.tar*`; scp ${PKG} geuzaine@getdp.info:.wwwgmsh/beta/${PKG/\.tar\.gz/c\.tgz}
    - ctest -j 8 --output-on-failure

# ------------------------------------------
# Official Linux builds (master branch only)
# ------------------------------------------

.linux_official_petsc_complex: &linux_official_petsc_complex
  only:
    - master@getdp/getdp
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGETDP_EXTRA_BUILD_NAME=-PetscComplex -DGETDP_HOST=getdp.info -DCMAKE_PREFIX_PATH=/usr/local -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc -DSLEPC_DIR=/home/geuzaine/src/slepc ${EXTRA_OPTION} ..
    - make package -j 1
    - PKG=`ls getdp-*.tar*`; scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/bin/Linux/${PKG/\.tar\.gz/c\.tgz}
    - /usr/local/bin/ctest -j 1 --output-on-failure

.linux_official_petsc_real: &linux_official_petsc_real
  only:
    - master@getdp/getdp
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGETDP_EXTRA_BUILD_NAME=-PetscReal -DGETDP_HOST=getdp.info -DCMAKE_PREFIX_PATH=/usr/local -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=real_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc -DSLEPC_DIR=/home/geuzaine/src/slepc ${EXTRA_OPTION} ..
    - make package -j 1
    - PKG=`ls getdp-*.tar*`; scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/bin/Linux/${PKG/\.tar\.gz/r\.tgz}
    - /usr/local/bin/ctest -j 1 --output-on-failure

.linux_official_petsc_real_mh: &linux_official_petsc_real_mh
  only:
    - master@getdp/getdp
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGETDP_EXTRA_BUILD_NAME=-PetscRealMH -DGETDP_HOST=getdp.info -DCMAKE_PREFIX_PATH=/usr/local -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=real_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc -DSLEPC_DIR=/home/geuzaine/src/slepc -DENABLE_MULTIHARMONIC=1 ${EXTRA_OPTION} ..
    - make package -j 1
    - PKG=`ls getdp-*.tar*`; scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/bin/Linux/${PKG/\.tar\.gz/r-MH\.tgz}
    - /usr/local/bin/ctest -j 1 --output-on-failure

linux64_official_petsc_complex_snapshot:
  <<: *linux_official_petsc_complex
  tags:
    - linux64
    - official
  except:
    - tags

linux64_official_petsc_complex_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *linux_official_petsc_complex
  tags:
    - linux64
    - official
  only:
    - /^getdp_.*$/

linux64_official_petsc_real_snapshot:
  <<: *linux_official_petsc_real
  tags:
    - linux64
    - official
  except:
    - tags

linux64_official_petsc_real_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *linux_official_petsc_real
  tags:
    - linux64
    - official
  only:
    - /^getdp_.*$/

linux64_official_petsc_real_mh_snapshot:
  <<: *linux_official_petsc_real_mh
  tags:
    - linux64
    - official
  except:
    - tags

linux64_official_petsc_real_mh_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *linux_official_petsc_real_mh
  tags:
    - linux64
    - official
  only:
    - /^getdp_.*$/

linux32_official_petsc_complex_snapshot:
  <<: *linux_official_petsc_complex
  tags:
    - linux32
    - official
  except:
    - tags

linux32_official_petsc_complex_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *linux_official_petsc_complex
  tags:
    - linux32
    - official
  only:
    - /^getdp_.*$/

linux32_official_petsc_real_snapshot:
  <<: *linux_official_petsc_real
  tags:
    - linux32
    - official
  except:
    - tags

linux32_official_petsc_real_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *linux_official_petsc_real
  tags:
    - linux32
    - official
  only:
    - /^getdp_.*$/

linux32_official_petsc_real_mh_snapshot:
  <<: *linux_official_petsc_real_mh
  tags:
    - linux32
    - official
  except:
    - tags

linux32_official_petsc_real_mh_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *linux_official_petsc_real_mh
  tags:
    - linux32
    - official
  only:
    - /^getdp_.*$/

# --------------------------------------------
# Official Windows builds (master branch only)
# --------------------------------------------

.windows_official_petsc_complex: &windows_official_petsc_complex
  only:
    - master@getdp/getdp
  script:
    - md build
    - cd build
    - bash -c "/usr/bin/cmake -DGETDP_EXTRA_BUILD_NAME=-PetscComplex -DGETDP_HOST=getdp.info -DCMAKE_PREFIX_PATH='/usr/local;/usr/mingw32/sys-root/mingw' -DCMAKE_C_COMPILER=/usr/bin/mingw32-gcc.exe -DCMAKE_CXX_COMPILER=/usr/bin/mingw32-g++.exe -DCMAKE_Fortran_COMPILER=/usr/bin/mingw32-gfortran.exe -DCMAKE_RC_COMPILER=/usr/bin/mingw32-windres.exe -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc -DSLEPC_DIR=/home/geuzaine/src/slepc ${EXTRA_OPTION} .."
    - bash -c "/usr/bin/make package -j 1"
    - bash -c "PKG=`ls getdp-*.zip`; /usr/bin/scp -o StrictHostKeyChecking=no -i /home/geuzaine/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/bin/Windows/${PKG/\.zip/c\.zip}"
    - bash -c "/usr/bin/ctest -j 1 --output-on-failure"

.windows_official_petsc_real: &windows_official_petsc_real
  only:
    - master@getdp/getdp
  script:
    - md build
    - cd build
    - bash -c "/usr/bin/cmake -DGETDP_EXTRA_BUILD_NAME=-PetscReal -DGETDP_HOST=getdp.info -DCMAKE_PREFIX_PATH='/usr/local;/usr/mingw32/sys-root/mingw' -DCMAKE_C_COMPILER=/usr/bin/mingw32-gcc.exe -DCMAKE_CXX_COMPILER=/usr/bin/mingw32-g++.exe -DCMAKE_Fortran_COMPILER=/usr/bin/mingw32-gfortran.exe -DCMAKE_RC_COMPILER=/usr/bin/mingw32-windres.exe -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=real_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc -DSLEPC_DIR=/home/geuzaine/src/slepc ${EXTRA_OPTION} .."
    - bash -c "/usr/bin/make package -j 1"
    - bash -c "PKG=`ls getdp-*.zip`; /usr/bin/scp -o StrictHostKeyChecking=no -i /home/geuzaine/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/bin/Windows/${PKG/\.zip/r\.zip}"
    - bash -c "/usr/bin/ctest -j 1 --output-on-failure"

.windows_official_petsc_real_mh: &windows_official_petsc_real_mh
  only:
    - master@getdp/getdp
  script:
    - md build
    - cd build
    - bash -c "/usr/bin/cmake -DGETDP_EXTRA_BUILD_NAME=-PetscRealMH -DGETDP_HOST=getdp.info -DCMAKE_PREFIX_PATH='/usr/local;/usr/mingw32/sys-root/mingw' -DCMAKE_C_COMPILER=/usr/bin/mingw32-gcc.exe -DCMAKE_CXX_COMPILER=/usr/bin/mingw32-g++.exe -DCMAKE_Fortran_COMPILER=/usr/bin/mingw32-gfortran.exe -DCMAKE_RC_COMPILER=/usr/bin/mingw32-windres.exe -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=real_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc -DSLEPC_DIR=/home/geuzaine/src/slepc -DENABLE_MULTIHARMONIC=1 ${EXTRA_OPTION} .."
    - bash -c "/usr/bin/make package -j 1"
    - bash -c "PKG=`ls getdp-*.zip`; /usr/bin/scp -o StrictHostKeyChecking=no -i /home/geuzaine/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/bin/Windows/${PKG/\.zip/r-MH\.zip}"
    - bash -c "/usr/bin/ctest -j 1 --output-on-failure"
  allow_failure: true

windows64_official_petsc_complex_snapshot:
  <<: *windows_official_petsc_complex
  tags:
    - windows64
    - official
  except:
    - tags

windows64_official_petsc_complex_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *windows_official_petsc_complex
  tags:
    - windows64
    - official
  only:
    - /^getdp_.*$/

windows64_official_petsc_real_snapshot:
  <<: *windows_official_petsc_real
  tags:
    - windows64
    - official
  except:
    - tags

windows64_official_petsc_real_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *windows_official_petsc_real
  tags:
    - windows64
    - official
  only:
    - /^getdp_.*$/

windows64_official_petsc_real_mh_snapshot:
  <<: *windows_official_petsc_real_mh
  tags:
    - windows64
    - official
  except:
    - tags

windows64_official_petsc_real_mh_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *windows_official_petsc_real_mh
  tags:
    - windows64
    - official
  only:
    - /^getdp_.*$/

windows32_official_petsc_complex_snapshot:
  <<: *windows_official_petsc_complex
  tags:
    - windows32
    - official
  except:
    - tags

windows32_official_petsc_complex_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *windows_official_petsc_complex
  tags:
    - windows32
    - official
  only:
    - /^getdp_.*$/

windows32_official_petsc_real_snapshot:
  <<: *windows_official_petsc_real
  tags:
    - windows32
    - official
  except:
    - tags

windows32_official_petsc_real_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *windows_official_petsc_real
  tags:
    - windows32
    - official
  only:
    - /^getdp_.*$/

windows32_official_petsc_real_mh_snapshot:
  <<: *windows_official_petsc_real_mh
  tags:
    - windows32
    - official
  except:
    - tags

windows32_official_petsc_real_mh_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *windows_official_petsc_real_mh
  tags:
    - windows32
    - official
  only:
    - /^getdp_.*$/

# ------------------------------------------
# Official MacOS builds (master branch only)
# ------------------------------------------

.macos_official_petsc_complex: &macos_official_petsc_complex
  only:
    - master@getdp/getdp
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGETDP_EXTRA_BUILD_NAME=-PetscComplex -DGETDP_HOST=getdp.info -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_C_COMPILER=/opt/local/bin/clang-mp-3.9 -DCMAKE_CXX_COMPILER=/opt/local/bin/clang++-mp-3.9 -DCMAKE_Fortran_COMPILER=/opt/local/bin/gfortran-mp-5 -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/Users/geuzaine/src/petsc -DSLEPC_DIR=/Users/geuzaine/src/slepc -DBLAS_LAPACK_LIBRARIES=/usr/local/lib/libopenblas.a ${EXTRA_OPTION} ..
    - make package -j 1
    - PKG=`ls getdp-*.tar*`
    - scp ${PKG} ace@ace36.montefiore.ulg.ac.be:/tmp
    - ssh ace@ace36.montefiore.ulg.ac.be /Users/ace/re-sign.sh /tmp/${PKG}
    - scp ace@ace36.montefiore.ulg.ac.be:/tmp/${PKG} .
    - scp ${PKG} geuzaine@getdp.info:.wwwgetdp/bin/MacOSX/${PKG/\.tar\.gz/c\.tgz}
    - /usr/local/bin/ctest -j 1 --output-on-failure

.macos_official_petsc_real: &macos_official_petsc_real
  only:
    - master@getdp/getdp
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGETDP_EXTRA_BUILD_NAME=-PetscReal -DGETDP_HOST=getdp.info -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_C_COMPILER=/opt/local/bin/clang-mp-3.9 -DCMAKE_CXX_COMPILER=/opt/local/bin/clang++-mp-3.9 -DCMAKE_Fortran_COMPILER=/opt/local/bin/gfortran-mp-5 -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=real_mumps_seq -DPETSC_DIR=/Users/geuzaine/src/petsc -DSLEPC_DIR=/Users/geuzaine/src/slepc -DBLAS_LAPACK_LIBRARIES=/usr/local/lib/libopenblas.a ${EXTRA_OPTION} ..
    - make package -j 1
    - PKG=`ls getdp-*.tar*`
    - scp ${PKG} ace@ace36.montefiore.ulg.ac.be:/tmp
    - ssh ace@ace36.montefiore.ulg.ac.be /Users/ace/re-sign.sh /tmp/${PKG}
    - scp ace@ace36.montefiore.ulg.ac.be:/tmp/${PKG} .
    - scp ${PKG} geuzaine@getdp.info:.wwwgetdp/bin/MacOSX/${PKG/\.tar\.gz/r\.tgz}
    - /usr/local/bin/ctest -j 1 --output-on-failure

.macos64_official_petsc_real_mh: &macos_official_petsc_real_mh
  only:
    - master@getdp/getdp
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGETDP_EXTRA_BUILD_NAME=-PetscRealMH -DGETDP_HOST=getdp.info -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_C_COMPILER=/opt/local/bin/clang-mp-3.9 -DCMAKE_CXX_COMPILER=/opt/local/bin/clang++-mp-3.9 -DCMAKE_Fortran_COMPILER=/opt/local/bin/gfortran-mp-5 -DENABLE_SPARSKIT=0 -DENABLE_PETSC=1 -DPETSC_ARCH=real_mumps_seq -DPETSC_DIR=/Users/geuzaine/src/petsc -DSLEPC_DIR=/Users/geuzaine/src/slepc -DENABLE_MULTIHARMONIC=1 -DBLAS_LAPACK_LIBRARIES=/usr/local/lib/libopenblas.a ${EXTRA_OPTION} ..
    - make package -j 1
    - PKG=`ls getdp-*.tar*`
    - scp ${PKG} ace@ace36.montefiore.ulg.ac.be:/tmp
    - ssh ace@ace36.montefiore.ulg.ac.be /Users/ace/re-sign.sh /tmp/${PKG}
    - scp ace@ace36.montefiore.ulg.ac.be:/tmp/${PKG} .
    - scp ${PKG} geuzaine@getdp.info:.wwwgetdp/bin/MacOSX/${PKG/\.tar\.gz/r-MH\.tgz}
    - /usr/local/bin/ctest -j 1 --output-on-failure

macos64_official_petsc_complex_snapshot:
  <<: *macos_official_petsc_complex
  tags:
    - macos64
    - official
  except:
    - tags

macos64_official_petsc_complex_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *macos_official_petsc_complex
  tags:
    - macos64
    - official
  only:
    - /^getdp_.*$/

macos64_official_petsc_real_snapshot:
  <<: *macos_official_petsc_real
  tags:
    - macos64
    - official
  except:
    - tags

macos64_official_petsc_real_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *macos_official_petsc_real
  tags:
    - macos64
    - official
  only:
    - /^getdp_.*$/

macos64_official_petsc_real_mh_snapshot:
  <<: *macos_official_petsc_real_mh
  tags:
    - macos64
    - official
  except:
    - tags

macos64_official_petsc_real_mh_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *macos_official_petsc_real_mh
  tags:
    - macos64
    - official
  only:
    - /^getdp_.*$/

# ----------------------------------------------
# Official source snapshots (master branch only)
# ----------------------------------------------

.source_official: &source_official
  only:
    - master@getdp/getdp
  script:
    - mkdir build_src
    - cd build_src
    - /usr/local/bin/cmake ${EXTRA_OPTION} ..
    - make package_source
    - PKG=`ls getdp-*.tar*`; scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ${PKG} geuzaine@getdp.info:.wwwgetdp/src/${PKG/\.tar\.gz/\.tgz}

source_official_snapshot:
  <<: *source_official
  tags:
    - linux64
    - official
  except:
    - tags

source_official_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  <<: *source_official
  tags:
    - linux64
    - official
  only:
    - /^getdp_.*$/

# ----------------------------------------------
# Official documentation (master branch only)
# ----------------------------------------------

doc_official_snapshot:
  only:
    - master@getdp/getdp
  script:
    - mkdir build_doc
    - cd build_doc
    - /usr/local/bin/cmake ${EXTRA_OPTION} ..
    - make doc
    - scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa getdp-*-doc.tgz geuzaine@getdp.info:.wwwgetdp/doc.tgz
    - ssh -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa geuzaine@getdp.info 'cd .wwwgetdp/dev && tar zxvf ../doc.tgz'
  tags:
    - linux64
    - official
  except:
    - tags

doc_official_release:
  variables:
    EXTRA_OPTION: "-DGETDP_RELEASE=1"
  only:
    - master@getdp/getdp
  script:
    - mkdir build_doc
    - cd build_doc
    - /usr/local/bin/cmake ${EXTRA_OPTION} ..
    - make doc
    - scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa getdp-*-doc.tgz geuzaine@getdp.info:.wwwgetdp/doc.tgz
    - ssh -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa geuzaine@getdp.info 'cd .wwwgetdp && tar zxvf doc.tgz'
    - scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ../doc/getdp.html geuzaine@getdp.info:.wwwgetdp/
  tags:
    - linux64
    - official
  only:
    - /^getdp_.*$/
